### ISSUE TITLE
Ошибка при сборке

### ISSUE THREAD

**Issue by loponavt** [insys-projects/gipcy#3]
Здравствуйте
При сборке gipcy возникает следующая ошибка:
![Снимок экрана от 2023-09-19 17-08-05](https://github.com/insys-projects/gipcy/assets/71023024/585a9c22-cbcf-4958-8aed-20c305aaae13)

**Comment by a-chernenko** [comment]
Наверное Вы собираете на новом ядре linux, которое еще не поддержано в gipcy.

**Comment by loponavt** [comment]
> Наверное Вы собираете на новом ядре linux, которое еще не поддержано в gipcy.

Да, все так, спасибо

**Comment by a-chernenko** [comment]
Если напишите на каком ядре ошибка, то можем исправить.

**Comment by loponavt** [comment]
> Если напишите на каком ядре ошибка, то можем исправить.

6.2.0-32-generic
